FinalTask.WebUI/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FinalTask.Domain.Entities;
using FinalTask.Domain.Infrastructure;
using FinalTask.WebUI.Areas.Admin.Models;
using Logger;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace FinalTask.WebUI.Areas.Admin.Controllers
{
    /// <summary>
    /// Handles all requests relating toadministrating user
    /// </summary>
    [Authorize(Roles = "Administrators")]
    public class AdminController : Controller
    {
        private readonly Loger _loger = new Loger(AppDomain.CurrentDomain.BaseDirectory, LogLevel.All, LogFormat.Xml);
        // GET: Admin/Admin
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }

        /// <summary>
        /// Disolays view to create user
        /// </summary>
        /// <returns></returns>
        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Create new user
        /// </summary>
        /// <param name="model">User to create</param>
        /// <returns></returns>
        // POST: Admin/Create
        [HttpPost]
        public async Task<ActionResult> Create(CreateModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Email, Email = model.Email };
                var result =
                    await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                }
            }
            return View(model);
        }
        
        /// <summary>
        /// Delete user
        /// </summary>
        /// <param name="id">User Id to delete</param>
        /// <returns></returns>
        //POST: Admin/Delete
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await UserManager.FindByIdAsync(id);

            if (user != null)
            {
                var result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new[] { "Користувача не знайдено" });
            }
        }

        /// <summary>
        /// Display user data  to edit
        /// </summary>
        /// <param name="id">User Id to edit</param>
        /// <returns></returns>
        //GET: Admin/Edit
        public async Task<ActionResult> Edit(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Edit user
        /// </summary>
        /// <param name="id">User ID to edit</param>
        /// <param name="email">user login</param>
        /// <param name="password">user password</param>
        /// <returns></returns>
        // POST: Admin/Edit
        [HttpPost]
        public async Task<ActionResult> Edit(string id, string email, string password)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                var validEmail
                    = await UserManager.UserValidator.ValidateAsync(user);

                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }

                IdentityResult validPass = null;
                if (password != string.Empty)
                {
                    validPass
                        = await UserManager.PasswordValidator.ValidateAsync(password);

                    if (validPass.Succeeded)
                    {
                        user.PasswordHash =
                            UserManager.PasswordHasher.HashPassword(password);
                    }
                    else
                    {
                        _loger.Log(validPass.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                        AddErrorsFromResult(validPass);
                    }
                }

                if (validPass != null && ((!validEmail.Succeeded || password == string.Empty || !validPass.Succeeded)))
                    return View(user);
                var result = await UserManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "Користувача не знйдено");
            }
            return View(user);
        }
        
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private AppUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
    }
}

FinalTask.WebUI/Areas/Admin/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FinalTask.Domain.Entities;
using FinalTask.Domain.Infrastructure;
using FinalTask.WebUI.Areas.Admin.Models;
using Logger;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace FinalTask.WebUI.Areas.Admin.Controllers
{
    /// <summary>
    /// Handles all requests relating to userroles
    /// </summary>
    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : Controller
    {
        private AppUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<AppUserManager>();

        private AppRoleManager RoleManager => HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();

        private readonly Loger _loger = new Loger(AppDomain.CurrentDomain.BaseDirectory, LogLevel.All, LogFormat.Xml);

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        /// <summary>
        /// Displays view to create new role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Create new role
        /// </summary>
        /// <param name="name">Role name</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (!ModelState.IsValid)
                return View(name);
            var result
                = await RoleManager.CreateAsync(new AppRole(name));

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                AddErrorsFromResult(result);
                _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
            }
            return View(name);
        }

        /// <summary>
        /// Delete role
        /// </summary>
        /// <param name="id">Role ID to delete</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new[] { "Роль не знайдена" });
            }
        }

        /// <summary>
        /// Edit Role
        /// </summary>
        /// <param name="id">Role Id to edit</param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            var memberIDs = role.Users.Select(x => x.UserId).ToArray();

            IEnumerable<AppUser> members
                = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));

            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);

            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        /// <summary>
        /// Edit role
        /// </summary>
        /// <param name="model">Edited role data</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model)
        {
            if (!ModelState.IsValid)
                return View("Error", new[] {"Роль не знайдена"});
            IdentityResult result;
            foreach (var userId in model.IdsToAdd ?? new string[] { })
            {
                result = await UserManager.AddToRoleAsync(userId, model.RoleName);

                if (!result.Succeeded)
                {
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                    return View("Error", result.Errors);
                }
            }
            foreach (var userId in model.IdsToDelete ?? new string[] { })
            {
                result = await UserManager.RemoveFromRoleAsync(userId,
                    model.RoleName);

                if (!result.Succeeded)
                {
                    _loger.Log(result.Errors.ToString(), LogLevel.Error, DateTime.Now, GetType().ToString());
                    return View("Error", result.Errors);
                }
            }
            return RedirectToAction("Index");
        }


        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

FinalTask.WebUI/Areas/Admin/Views/Admin/Create.cshtml
@model FinalTask.WebUI.Areas.Admin.Models.CreateModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Створити" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутися до списку користувачів", "Index")
</div>

FinalTask.WebUI/Areas/Admin/Views/Admin/Edit.cshtml
@model FinalTask.Domain.Entities.AppUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Редагувати користувача</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутися до списку користувачів", "Index", new {@class = "btn btn-primary" })
</div>

FinalTask.WebUI/Areas/Admin/Views/Admin/Index.cshtml
@using FinalTask.Domain.Entities
@model IEnumerable<FinalTask.Domain.Entities.AppUser>

@{
    ViewBag.Title = "Адміністратор";
}
<p align="right"><a href="Account/Logout" class="btn btn-primary">Вийти</a></p>
<p>@Html.ActionLink("Ролі", "Index", "RoleAdmin", null, new { @class = "btn btn-primary" })</p>
<p><a href="Visit/Index" class="btn btn-primary">Обліковий запис</a></p>
<div class="panel panel-primary">
    <div class="panel-heading">
        Облікові записи
    </div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Ім'я</th>
            <th>Email</th>
        </tr>
        @if (!Model.Any())
        {
            <tr>
                <td colspan="3" class="text-center">Немає жодного облікового запису</td>
            </tr>
        }
        else
        {
            foreach (var user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td>
                        @using (Html.BeginForm("Delete", "Admin", new { id = user.Id }))
                        {
                            @Html.ActionLink("Редагувати", "Edit", new { id = user.Id },
                                               new { @class = "btn btn-primary btn-xs", style = "float: left; margin-right: 10px" })
                            <button class="btn btn-danger btn-xs" type="submit">Видалити</button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
<p>@Html.ActionLink("Створити", "Create", null, new { @class = "btn btn-primary" })</p>